# Generated by Django 3.1.13 on 2025-01-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20250102_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remise',
        ),
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='livraison_facture',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='prenom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='produit',
        ),
        migrations.AlterField(
            model_name='order',
            name='remise_finale',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('En cours', 'En cours'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='Nouvelle', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cout_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='produit',
            field=models.ManyToManyField(through='crm.OrderProduct', to='crm.Product'),
        ),
    ]
